### ISSUE TITLE
improve model logic

### ISSUE THREAD

**Issue by cluelessjoe** [cluelessjoe/todoMVC-cyclejs-typescript#2]

**Comment by cluelessjoe** [comment]
looks like it can be merged back into master: do not hesitate IMHO (so I could based routing on top of it :))

**Comment by o-schneider** [comment]
All right, I just wanted to have a quick review before, to see if we agree on the principle. :)
If it's ok, I'll merge it then. ;)

**Comment by o-schneider** [comment]
Merged with 84582e2a0e3c6ec1ea2f8886dd170cd836e1a12e.
